name: Test

on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages
        working-directory: ./hosting
        run: npm ci

      - name: lint project
        working-directory: ./hosting
        run: npm run lint


      # currently tests are broken, will be fixed later again
      # - name: run unit tests
      #   working-directory: ./hosting
      #   run: npm run test:ci

  build_angular_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages
        working-directory: ./hosting
        run: npm ci

      - name: build angular app
        working-directory: ./hosting
        run: npm run build:prod

  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages
        working-directory: ./functions
        run: npm ci

      - name: lint project
        working-directory: ./functions
        run: npm run lint

      - name: build functions
        working-directory: ./functions
        run: npm run build
